############################### Comments ############################### > start
comments:
  title: <i class='fa-solid fa-comments'></i> è¯„è®º
  subtitle:
  service: artalk
  # å¯é€‰è¯„è®ºç³»ç»Ÿ #
  
  # artalk
  # https://artalk.js.org/
  # https://github.com/ArtalkJS/Artalk
  artalk:
    server: https://yours-artalk-domain    # ä¿®æ”¹ä¸ºè‡ªå»ºçš„åŽç«¯æœåŠ¡åœ°å€
    path:  # å…¨å±€è¯„è®ºåœ°å€
    placeholder: # è¯„è®ºå ä½
    visitor: true # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« é˜…è¯»æ•°
    latex: false # å¯ç”¨ Latex æ”¯æŒ
    # artalk æœ‰ä¸‰ç±»å›¾ç‰‡ï¼š1.ä¸Šä¼ è‡³æœåŠ¡ç«¯ 2.ä¸Šä¼ è‡³æœåŠ¡ç«¯åŽåˆ©ç”¨upgitä¸Šä¼ è‡³å›¾åºŠ 3.å‰ç«¯ä¸Šä¼ è‡³å›¾åºŠï¼ˆæœ¬é…ç½®ä¸ºæ­¤ç±»ï¼‰
    # é…ç½®æ­¤é¡¹æ—¶å°†è¦†ç›–æœåŠ¡ç«¯ä¸Šä¼ èƒ½åŠ›
    imageUploader:
      # ä»¥å…°ç©ºå›¾åºŠä¸ºä¾‹ï¼Œä¸‹åˆ—å¡«å†™å†…å®¹ä¸ºï¼š
      # url: 'https://xxxxxx/api/v1/upload'
      # token: 'Bearer xxxxxxxxxxxxxx'
      # resp: 'data.links.url'
      api: # å›¾åºŠåœ°å€
      token: # å›¾åºŠéªŒè¯
      resp: # å›¾ç‰‡åœ°å€è¿”å›žå€¼çš„å­—æ®µ
    # æ›´å¤šç½®é¡¹å¯åœ¨ Artalk åŽç«¯è¿›è¡Œé…ç½®ï¼Œè¯¦è§ https://artalk.js.org/guide/backend/fe-control.html
    # ä¹Ÿå¯ä»¥åœ¨æ­¤å¤„ç»§ç»­å‚è€ƒä¸Šæ–¹ä¾‹å­è¿›è¡Œé…ç½®ï¼Œä¸å»ºè®®é‡å†™é…ç½®çš„å­—æ®µé™¤ä¸Šæ–¹æ‰€è¿°å¤–è¿˜æœ‰ï¼š
    # [el, useBackendConf, pageKey, pageTitle, site, darkMode, pvEl, imgUploader]
############################### Comments ############################### > end

############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [license, info, copyright]
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  # analytics using busuanzi
  analytics: >
    <a title="æ— èŠæ¹¾ ðŸ¥± The Boring Bay" href="https://boringbay.com"><img height="18px" src="https://boringbay.com/api/badge/wuminboke.site"></img></a>
  # site copyright
  copyright: '(CC BY-NC-SA 4.0)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
############################### Site Footer ############################### > end

######## Plugins to optimize the experience:
  # prismjs
  # https://prismjs.com/
  # https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS
  prismjs:
    copy_code: true
    # Please set hexo.config.highlight.enable = false !!! set hexo.config.prismjs.enable = true !!!
    js:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/components/prism-core.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/prism.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.css