#Msic
dns_prefetch:
  - https://cdnjs.cloudflare.com
  
sidebar:
  position: right
  # ä¸»é¡µã€åˆ†ç±»ã€å½’æ¡£ç­‰ç‹¬ç«‹é¡µé¢
  for_page: [blogger]
  # layout: docs/post è¿™ç±»æ–‡ç« é¡µé¢
  for_post: [blogger, toc]
  
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://bu.dusays.com/2024/07/23/669f7b016ad0b.jpg
      title: æ— ååšå®¢
      subtitle: ä¸€ä¸ªæ— èŠçš„äººç½¢äº†~
      jinrishici: false
      social: false
  
############################### Navigation Bar ############################### > start
# æ³¨æ„äº‹é¡¹ï¼šå»ºè®®è§„èŒƒå…¨ç«™è·¯å¾„ URL æœ€åŽå¸¦ä¸€ä¸ª "/" ä¾‹å¦‚ "about/"
navbar:
  visiable: always # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon: https://bu.dusays.com/2024/07/23/669f7b016ad0b.jpg
    title: æ— ååšå®¢
  menu:
    - name: åšå®¢
      icon: fa-solid fa-rss
      url: /
    - name: å½’æ¡£
      icon: fa-solid fa-archive
      url: archives/
    - name: å‹é“¾
      icon: fa-solid fa-link
      url: friends/
    - name: å…³äºŽ
      icon: fa-solid fa-info-circle
      url: about/
  search: Search...   # Search bar placeholder
############################### Navigation Bar ############################### > end
  
############################### Cover ############################### > start
cover:
  height_scheme:  # full, half
  layout_scheme: search # blank (ç•™ç™½), search (æœç´¢), dock (åž), featured (ç²¾é€‰), focus (ç„¦ç‚¹)

############################### Comments ############################### > start
comments:
  title: <i class='fa-solid fa-comments'></i> è¯„è®º
  subtitle:
  service: artalk
  # å¯é€‰è¯„è®ºç³»ç»Ÿ #
  
  # artalk
  # https://artalk.js.org/
  # https://github.com/ArtalkJS/Artalk
  artalk:
    server: https://yours-artalk-domain    # ä¿®æ”¹ä¸ºè‡ªå»ºçš„åŽç«¯æœåŠ¡åœ°å€
    path:  # å…¨å±€è¯„è®ºåœ°å€
    placeholder: # è¯„è®ºå ä½
    visitor: true # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« é˜…è¯»æ•°
    latex: false # å¯ç”¨ Latex æ”¯æŒ
    # artalk æœ‰ä¸‰ç±»å›¾ç‰‡ï¼š1.ä¸Šä¼ è‡³æœåŠ¡ç«¯ 2.ä¸Šä¼ è‡³æœåŠ¡ç«¯åŽåˆ©ç”¨upgitä¸Šä¼ è‡³å›¾åºŠ 3.å‰ç«¯ä¸Šä¼ è‡³å›¾åºŠï¼ˆæœ¬é…ç½®ä¸ºæ­¤ç±»ï¼‰
    # é…ç½®æ­¤é¡¹æ—¶å°†è¦†ç›–æœåŠ¡ç«¯ä¸Šä¼ èƒ½åŠ›
    imageUploader:
      # ä»¥å…°ç©ºå›¾åºŠä¸ºä¾‹ï¼Œä¸‹åˆ—å¡«å†™å†…å®¹ä¸ºï¼š
      # url: 'https://xxxxxx/api/v1/upload'
      # token: 'Bearer xxxxxxxxxxxxxx'
      # resp: 'data.links.url'
      api: # å›¾åºŠåœ°å€
      token: # å›¾åºŠéªŒè¯
      resp: # å›¾ç‰‡åœ°å€è¿”å›žå€¼çš„å­—æ®µ
    # æ›´å¤šç½®é¡¹å¯åœ¨ Artalk åŽç«¯è¿›è¡Œé…ç½®ï¼Œè¯¦è§ https://artalk.js.org/guide/backend/fe-control.html
    # ä¹Ÿå¯ä»¥åœ¨æ­¤å¤„ç»§ç»­å‚è€ƒä¸Šæ–¹ä¾‹å­è¿›è¡Œé…ç½®ï¼Œä¸å»ºè®®é‡å†™é…ç½®çš„å­—æ®µé™¤ä¸Šæ–¹æ‰€è¿°å¤–è¿˜æœ‰ï¼š
    # [el, useBackendConf, pageKey, pageTitle, site, darkMode, pvEl, imgUploader]
############################### Comments ############################### > end

############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [source, analytics, copyright]
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  # analytics using busuanzi
  analytics: >
    <a title="æ— èŠæ¹¾ ðŸ¥± The Boring Bay" href="https://boringbay.com"><img height="18px" src="https://boringbay.com/api/badge/wuminboke.site"></img></a>
  # site copyright
  copyright: '(CC BY-NC-SA 4.0)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
############################### Site Footer ############################### > end

######## Plugins to optimize the experience:
  # prismjs
  # https://prismjs.com/
  # https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS
  prismjs:
    copy_code: true
    # Please set hexo.config.highlight.enable = false !!! set hexo.config.prismjs.enable = true !!!
    js:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/components/prism-core.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/prism.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.css