#Msic
dns_prefetch:
  - https://cdnjs.cloudflare.com
  
sidebar:
  position: right
  # ‰∏ªÈ°µ„ÄÅÂàÜÁ±ª„ÄÅÂΩíÊ°£Á≠âÁã¨Á´ãÈ°µÈù¢
  for_page: [blogger]
  # layout: docs/post ËøôÁ±ªÊñáÁ´†È°µÈù¢
  for_post: [blogger, toc]
  
  widget_library:
    blogger:
      class: blogger
      display: [desktop] # [desktop, mobile]
      avatar: https://bu.dusays.com/2024/07/23/669f7b016ad0b.jpg
      title: Êó†ÂêçÂçöÂÆ¢
      subtitle: ‰∏Ä‰∏™Êó†ËÅäÁöÑ‰∫∫ÁΩ¢‰∫Ü~
      jinrishici: false
      social: false
  
############################### Navigation Bar ############################### > start
# Ê≥®ÊÑè‰∫ãÈ°πÔºöÂª∫ËÆÆËßÑËåÉÂÖ®Á´ôË∑ØÂæÑ URL ÊúÄÂêéÂ∏¶‰∏Ä‰∏™ "/" ‰æãÂ¶Ç "about/"
navbar:
  visiable: always # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon: https://bu.dusays.com/2024/07/23/669f7b016ad0b.jpg
    title: Êó†ÂêçÂçöÂÆ¢
  menu:
    - name: ÂçöÂÆ¢
      icon: fa-solid fa-rss
      url: /
    - name: ÂΩíÊ°£
      icon: fa-solid fa-archive
      url: archives/
  search: ÊêúÁ¥¢‰∏çÂèØÁî®...
############################### Navigation Bar ############################### > end
  
############################### Cover ############################### > start
cover:
  height_scheme:  # full, half
  layout_scheme: search # blank (ÁïôÁôΩ), search (ÊêúÁ¥¢), dock (Âùû), featured (Á≤æÈÄâ), focus (ÁÑ¶ÁÇπ)

############################### Comments ############################### > start
comments:
  title: <i class='fa-solid fa-comments'></i> ËØÑËÆ∫
  subtitle:
  service: artalk
  # ÂèØÈÄâËØÑËÆ∫Á≥ªÁªü #
  
  # artalk
  # https://artalk.js.org/
  # https://github.com/ArtalkJS/Artalk
  artalk:
    server: https://yours-artalk-domain    # ‰øÆÊîπ‰∏∫Ëá™Âª∫ÁöÑÂêéÁ´ØÊúçÂä°Âú∞ÂùÄ
    path:  # ÂÖ®Â±ÄËØÑËÆ∫Âú∞ÂùÄ
    placeholder: # ËØÑËÆ∫Âç†‰Ωç
    visitor: true # ÊòØÂê¶ÊòæÁ§∫ÊñáÁ´†ÈòÖËØªÊï∞
    latex: false # ÂêØÁî® Latex ÊîØÊåÅ
    # artalk Êúâ‰∏âÁ±ªÂõæÁâáÔºö1.‰∏ä‰º†Ëá≥ÊúçÂä°Á´Ø 2.‰∏ä‰º†Ëá≥ÊúçÂä°Á´ØÂêéÂà©Áî®upgit‰∏ä‰º†Ëá≥ÂõæÂ∫ä 3.ÂâçÁ´Ø‰∏ä‰º†Ëá≥ÂõæÂ∫äÔºàÊú¨ÈÖçÁΩÆ‰∏∫Ê≠§Á±ªÔºâ
    # ÈÖçÁΩÆÊ≠§È°πÊó∂Â∞ÜË¶ÜÁõñÊúçÂä°Á´Ø‰∏ä‰º†ËÉΩÂäõ
    imageUploader:
      # ‰ª•ÂÖ∞Á©∫ÂõæÂ∫ä‰∏∫‰æãÔºå‰∏ãÂàóÂ°´ÂÜôÂÜÖÂÆπ‰∏∫Ôºö
      # url: 'https://xxxxxx/api/v1/upload'
      # token: 'Bearer xxxxxxxxxxxxxx'
      # resp: 'data.links.url'
      api: # ÂõæÂ∫äÂú∞ÂùÄ
      token: # ÂõæÂ∫äÈ™åËØÅ
      resp: # ÂõæÁâáÂú∞ÂùÄËøîÂõûÂÄºÁöÑÂ≠óÊÆµ
    # Êõ¥Â§öÁΩÆÈ°πÂèØÂú® Artalk ÂêéÁ´ØËøõË°åÈÖçÁΩÆÔºåËØ¶ËßÅ https://artalk.js.org/guide/backend/fe-control.html
    # ‰πüÂèØ‰ª•Âú®Ê≠§Â§ÑÁªßÁª≠ÂèÇËÄÉ‰∏äÊñπ‰æãÂ≠êËøõË°åÈÖçÁΩÆÔºå‰∏çÂª∫ËÆÆÈáçÂÜôÈÖçÁΩÆÁöÑÂ≠óÊÆµÈô§‰∏äÊñπÊâÄËø∞Â§ñËøòÊúâÔºö
    # [el, useBackendConf, pageKey, pageTitle, site, darkMode, pvEl, imgUploader]
############################### Comments ############################### > end

############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [source, analytics, copyright, moe-icp]
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  # analytics using busuanzi
  analytics: >
    <a title="Êó†ËÅäÊπæ ü•± The Boring Bay" href="https://boringbay.com"><img height="18px" src="https://boringbay.com/api/badge/wuminboke.site"></img></a>
  # site copyright
  copyright: '(CC BY-NC-SA 4.0)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
  moe-icp: "<a href=\"https://icp.gov.moe/?keyword=20245354\" target=\"_blank\">ËêåICPÂ§á20245354Âè∑</a>"
############################### Site Footer ############################### > end

######## Plugins to optimize the experience:
  # prismjs
  # https://prismjs.com/
  # https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS
  prismjs:
    copy_code: true
    # Please set hexo.config.highlight.enable = false !!! set hexo.config.prismjs.enable = true !!!
    js:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/components/prism-core.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/prism.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.css