#Msic
dns_prefetch:
  - https://cdnjs.cloudflare.com
  
sidebar:
  position: right
  # ä¸»é¡µã€åˆ†ç±»ã€å½’æ¡£ç­‰ç‹¬ç«‹é¡µé¢
  for_page: [blogger]
  # layout: docs/post è¿™ç±»æ–‡ç« é¡µé¢
  for_post: [blogger, toc]
  
  widget_library:
    blogger:
      class: blogger
      display: [desktop, mobile] # [desktop, mobile]
      avatar: https://bu.dusays.com/2024/07/28/66a6341c04222.jpg
      title: æ— ååšå®¢
      subtitle: ä¸€ä¸ªæ— èŠçš„äººç½¢äº†~
      jinrishici: false
      social: false
      
# æ–‡ç« å¸ƒå±€
article:
   # æ–‡ç« è¯¦æƒ…é¡µé¢çš„æ–‡ç« å¡ç‰‡æœ¬ä½“å¸ƒå±€æ–¹æ¡ˆ
  body:
    # æ–‡ç« é¡¶éƒ¨ä¿¡æ¯
    # ä» meta_library ä¸­å–
    top_meta: [author, category, date, counter]
    # ----------------
    # æ–‡ç« é¡µè„šç»„ä»¶
    footer_widget:
      # ç‰ˆæƒå£°æ˜ç»„ä»¶ (for layout: post/docs)
      copyright:
        enable: true
        permalink: 'æœ¬æ–‡æ°¸ä¹…é“¾æ¥æ˜¯ï¼š'
        content:
          - 'åšå®¢å†…å®¹éµå¾ª ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº« 4.0 å›½é™… (CC BY-NC-SA 4.0) åè®®'
          - permalink
      # ----------------
      # æ‰“èµç»„ä»¶ (for layout: post/docs)
      donate:
        enable: true
        images:
          - https://bu.dusays.com/2024/07/23/669f9a2d83d4d.png #Stripe
    
############################# Analytics ############################# > start
analytics:
  busuanzi: https://npm.elemecdn.com/penndu@1.0.0/bsz.js # ä¿®æ”¹è¿™é‡Œå³å¯
############################# Analytics ############################# > end
  
############################### Navigation Bar ############################### > start
# æ³¨æ„äº‹é¡¹ï¼šå»ºè®®è§„èŒƒå…¨ç«™è·¯å¾„ URL æœ€åå¸¦ä¸€ä¸ª "/" ä¾‹å¦‚ "about/"
navbar:
  visiable: always # always, auto
  logo: # choose [img] or [icon + title]
    img:
    icon: https://bu.dusays.com/2024/07/28/66a6341c04222.jpg
    title: æ— ååšå®¢
  menu:
    - name: åšå®¢
      icon: fa-solid fa-rss
      url: /
    - name: å½’æ¡£
      icon: fa-solid fa-archive
      url: archives/
    - name: å‹é“¾
      icon: fa-solid fa-user-group
      url: https://wuminboke.site/2024/07/23/Misc/#å‹é“¾
    - name: èµåŠ©
      icon: fa-brands fa-alipay
      url: https://wuminboke.site/2024/07/23/Misc/#èµåŠ©
  search: æœç´¢ä¸å¯ç”¨...
############################### Navigation Bar ############################### > end
  
############################### Cover ############################### > start
cover:
  height_scheme:  # full, half
  layout_scheme: blank # blank (ç•™ç™½), search (æœç´¢), dock (å), featured (ç²¾é€‰), focus (ç„¦ç‚¹)
  display:
    home: false
############################### Comments ############################### > start
comments:
  title: <i class='fa-solid fa-comments'></i> è¯„è®º
  subtitle:
  service: utterances
  # å¯é€‰è¯„è®ºç³»ç»Ÿ #
  
  # utterances
  # https://utteranc.es/
  utterances:
    repo: wumingblog/hexo
    issue-term: pathname
    issue-number:
    theme:
      light: github-light
      dark: github-dark
    label: âœ¨ğŸ’¬âœ¨
  ####å›è°ƒä¸æ­£ç¡®####
  beaudar:
    repo: wumingblog/hexo
    issue-term: pathname
    issue-number:
    branch: main
    position: top
    order: desc
    theme:
      light: github-light
      dark: github-dark
    label: âœ¨ğŸ’¬âœ¨
############################### Comments ############################### > end

############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  layout: [source, analytics, copyright, moe-icp, feed]
  # site source
  source: https://github.com/volantis-x/volantis-docs/
  # analytics using busuanzi
  analytics: >
    <a title="æ— èŠæ¹¾ ğŸ¥± The Boring Bay" href="https://boringbay.com"><img height="18px" src="https://boringbay.com/api/badge/wuminboke.site"></img></a>
    <span>æœ¬ç«™æ€»è®¿é—®é‡ä¸º <span id='busuanzi_value_site_pv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> æ¬¡</span>
    <span>è®¿å®¢æ•°ä¸º <span id='busuanzi_value_site_uv'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> äºº</span>
  # site copyright
  copyright: '(CC BY-NC-SA 4.0) (Avatar: CC BY-NC-ND 4.0)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'
  moe-icp: "<a href=\"https://icp.gov.moe/?keyword=20235354\" target=\"_blank\">èŒICPå¤‡20235354å·</a>"
  feed: "<a href=\"https://wuminboke.site/atom.xml\">Feed(Atom.xml)</a>"
############################### Site Footer ############################### > end

######## Plugins to optimize the experience:
  # prismjs
  # https://prismjs.com/
  # https://hexo.io/zh-cn/docs/syntax-highlight#PrismJS
  prismjs:
    copy_code: true
    # Please set hexo.config.highlight.enable = false !!! set hexo.config.prismjs.enable = true !!!
    js:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/components/prism-core.min.js
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.js
    css:
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/themes/prism.min.css
      - https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/plugins/line-numbers/prism-line-numbers.min.css
######## Plugins for Count:
  busuanzi:
    enable: #true
